version: '3.5'
services:
  redis:
    image: redis:5
    ports:
      - 6379:6379
    networks:
      - webnet
  postgres:
    image: postgres:11
    volumes:
      - data-volume:/data/db
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: order-backend
    networks:
      - webnet
networks:
  webnet:
volumes:
  data-volume:
